/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package marchandise;

import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Az Zahroh
 */
public class detail extends javax.swing.JInternalFrame {

    /**
     * Creates new form detail
     */
    DefaultTreeModel model;
    public detail() {
        initComponents();
    }
DefaultMutableTreeNode detail = new DefaultMutableTreeNode("Detail Product");
public void Load()
{
    DefaultMutableTreeNode albumNode = new DefaultMutableTreeNode("Album");
    albumNode.add(new DefaultMutableTreeNode("Clé: Levanter"));
    albumNode.add(new DefaultMutableTreeNode(";[Semicolon]"));
    albumNode.add(new DefaultMutableTreeNode("We Boom"));
    albumNode.add(new DefaultMutableTreeNode("Go"));
    albumNode.add(new DefaultMutableTreeNode("Chain"));
    albumNode.add(new DefaultMutableTreeNode("Maxident"));
    albumNode.add(new DefaultMutableTreeNode("Attaca"));
    albumNode.add(new DefaultMutableTreeNode("Glitch Mode"));
    DefaultMutableTreeNode lightNode = new DefaultMutableTreeNode("Lightstick");
    lightNode.add(new DefaultMutableTreeNode("NCT"));
    lightNode.add(new DefaultMutableTreeNode("SEVENTEEN"));
    lightNode.add(new DefaultMutableTreeNode("STRAY KIDS"));
    lightNode.add(new DefaultMutableTreeNode("NEW JEANS"));
    lightNode.add(new DefaultMutableTreeNode("(G)I-DLE"));
    lightNode.add(new DefaultMutableTreeNode("TREASURE"));
    lightNode.add(new DefaultMutableTreeNode("RED VELVET"));
    lightNode.add(new DefaultMutableTreeNode("BTS"));
    detail.add(albumNode);
    detail.add(lightNode);
    model = (DefaultTreeModel)jTree1.getModel();
    model.setRoot(detail);
    jTree1.setModel(model);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Artist = new javax.swing.JTextField();
        Release = new javax.swing.JTextField();
        Photocard = new javax.swing.JTextField();

        setClosable(true);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Detail Product");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Album");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Clé: Levanter");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode(";[Semicolon]");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("We Boom");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Go Live");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Chain");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Maxident");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Attaca");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Glitch Mode");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Lightstick");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("NCT");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("SEVENTEEN");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("STRAY KIDS");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("NEW JEANS");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("(G)I-DLE");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("TREASURE");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("RED VELVET");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("BTS");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel1.setText("NAME");

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel2.setText("ARTIST");

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel3.setText("RELEASE");

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel4.setText("PHOTOCARD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Name)
                    .addComponent(Artist)
                    .addComponent(Release)
                    .addComponent(Photocard, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Artist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Release, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Photocard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
detail = (DefaultMutableTreeNode)jTree1.getSelectionPath().getLastPathComponent();
Name.setText(detail.getUserObject().toString());
String select = detail.getUserObject().toString();
        switch (select) {
            case "Clé: Levanter":
                Artist.setText("STRAY KIDS");
                Release.setText("2019-12-09");
                Photocard.setText("Random 3p out of 40p");
                break;
            case ";[Semicolon]":
                Artist.setText("SEVENTEEN");
                Release.setText("2020-10-19");
                Photocard.setText("Random 2p out of 26p");
                break;
            case "We Boom":
                Artist.setText("NCT DREAM");
                Release.setText("2019-07-30");
                Photocard.setText("Random 1p out of 6p");
                break;
            case "Go":
                Artist.setText("STRAY KIDS");
                Release.setText("2020-06-18");
                Photocard.setText("Random 2p out of 40p");
                break;
            case "Chain":
                Artist.setText("NCT 127");
                Release.setText("2018-05-23");
                Photocard.setText("Random 1p out of 9p");
                break;
            case "Maxident":
                Artist.setText("STRAY KIDS");
                Release.setText("2022-07-10");
                Photocard.setText("Random 2p out of 24p");
                break;
            case "Attaca":
                Artist.setText("SEVENTEEN");
                Release.setText("2021-10-22");
                Photocard.setText("Random 2p out of 26p");
                break;
            case "Glitch Mode":
                Artist.setText("NCT DREAM");
                Release.setText("2022-03-29");
                Photocard.setText("Random 1p out of 7p");
                break;
            case "NCT":
                Artist.setText("NCT");
                Release.setText("2018-06-17");
                Photocard.setText("--none--");
                break;
            case "SEVENTEEN":
                Artist.setText("SEVENTEEN");
                Release.setText("2019-07-29");
                Photocard.setText("--none--");
                break;
            case "NEW JEANS":
                Artist.setText("NEW JEANS");
                Release.setText("2023-03-07");
                Photocard.setText("5ea");
                break;
            case "STRAY KIDS":
                Artist.setText("STRAY KIDS");
                Release.setText("2019-11-23");
                Photocard.setText("--none--");
                break;
            case "(G)I-DLE":
                Artist.setText("(G)I-DLE");
                Release.setText("2023-01-05");
                Photocard.setText("--none--");
                break;
            case "TREASURE":
                Artist.setText("TREASURE");
                Release.setText("2023-03-24");
                Photocard.setText("Random 1p out of 12p");
                break;
            case "RED VELVET":
                Artist.setText("RED VELVET");
                Release.setText("2018-07-23");
                Photocard.setText("--none--");
                break;
            case "BTS":
                Artist.setText("BTS");
                Release.setText("2018-07-27");
                Photocard.setText("7ea");
                break;
            default:
                break;
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTree1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Artist;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Photocard;
    private javax.swing.JTextField Release;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
